
@startuml
title Modelo de Pregunta usando Simple Factory
skinparam classAttributeIconSize 0

class PreguntaCreador{
    + crearPregunta(tipoPregunta: TipoPregunta): Preguntable
}

interface Preguntable{
    + obtenerOpciones():List
    + establecerPuntuacion(opciones:List): int
    + obtenerPregunta():str
}

enum TipoPreguntaConcreta{
    VerdaderoFalsoClasico
    VerdaderoFalsoPenalidad
}

abstract class VerdaderoFalso{
    
}

' sin penalidad
class VerdaderoFalsoClasico{
}

class Multiplie_Clasico{

}

class Multiple_Parcial{
    
}

' con penalidad
class VerdaderoFalsoPenalidad{
}

class Multiple_Penal{
}


' Especiales
class GroupChoice{
}

class OpcionesOrdenadas{
}


PreguntaCreador -down->TipoPreguntaConcreta
PreguntaCreador -> Preguntable

Preguntable <.. VerdaderoFalso

' Preg_Penal
VerdaderoFalso <|-- VerdaderoFalsoPenalidad
Preguntable <.. Multiple_Penal


' Pregun_Sin_Penal
VerdaderoFalso <|-- VerdaderoFalsoClasico
Preguntable <.. Multiplie_Clasico
Preguntable <.. Multiple_Parcial

Preguntable <.. GroupChoice
Preguntable <.. OpcionesOrdenadas

@enduml