@startuml
title Diagrama de secuencia conectando Vista con Controlador
hide footbox

create App
create ":Kahoot" as Kahoot
App -> Kahoot

Kahoot -> Kahoot: iniciar()


create "pantallaPrincal:PantallaPrincipal" as PantallaPrincipal
Kahoot -> PantallaPrincipal: <<create>>

create ":PanelInicial" as PanelInicial
PantallaPrincipal -> PanelInicial: <<create>>

create ":PanelPregunta" as PanelPregunta
PantallaPrincipal -> PanelPregunta: <<create>>


PantallaPrincipal -> PantallaPrincipal: configurarPantallaPrincipal()

create ":ControladorPanel" as ControladorPanel
Kahoot -> ControladorPanel: << create(pantallaPrincipal) >>

PantallaPrincipal -> PantallaPrincipal: conectaControladorPrincipal(controladorPanel)

@enduml