@startuml
title Diagrama de clase del modelo MVC
skinparam classAttributeIconSize 0
hide circle


class ModeloKahoot{
    
}

class VistaKahoot{

}

class Controlador{

}


VistaKahoot <-> Controlador
Controlador --> ModeloKahoot
VistaKahoot --> ModeloKahoot



@enduml