@startuml
title Creación MultipleChoice Clasico Con Opciones Validas

Kahoot -> CreadorPregunta: CreadorPregunta.crearPregunta(TipoPregunta.MultipleChoiceClasico, pregunta, opciones)
CreadorPregunta -> MultipleChoiceClasico: new MultipleChoiceClasico(pregunta, opciones)

activate MultipleChoiceClasico
MultipleChoiceClasico -> MultipleChoiceClasico: validarOpciones(opciones)
MultipleChoiceClasico -> CreadorPregunta: new MultipleChoiceClasico(pregunta, opciones)
deactivate MultipleChoiceClasico

CreadorPregunta --> Kahoot: new MultipleChoiceClasico(pregunta, opciones)
@enduml