@startuml
title Modelo de Multiplicador
skinparam classAttributeIconSize 0


class Ronda{
    - jugadores: List<Jugador>
    - pregunta: Preguntable

    + obtenerJugadores(): List<Jugador>
    + obtenerPregunta():Preguntable
    + responder(jugador: Jugador, opciones: List<Opcion>):void
    + responder(jugador: Jugador, opciones: List<Opcion>, multiplicador: MultiplicableStrategy):void
}

interface MultiplicableStrategy{
    + aplicarMultiplicador(puntos: int): int
}

enum Multiplicador{
    PorDefecto
    PorDos
    PorTres
}


Ronda --> MultiplicableStrategy

MultiplicableStrategy <|.. Multiplicador

@enduml