@startuml
!include vista.iuml
title Modelo de Multiplicador

interface Preguntable{
    + obtenerOpciones():List
    + establecerPuntuacion(opciones:List): int
    + establecerPuntuacion(opciones: List<Opcion>, multiplicador: MultiplicableStrategy): int
    + obtenerPregunta():str
}

interface MultiplicableStrategy{
    + aplicarMultiplicador(puntos: int): int
}

enum Multiplicador{
    PorDefecto
    PorDos
    PorTres
}


Preguntable --> MultiplicableStrategy

MultiplicableStrategy <|.. Multiplicador

@enduml