@startuml
title Diagrama de Paquetes del modelo MVC
hide circle

package ModeloKahoot{
}

package VistaKahoot{
}

package Controlador{

}

Controlador --> ModeloKahoot
VistaKahoot --> ModeloKahoot
VistaKahoot <-> Controlador

@enduml