@startuml alResponderIncorrectamenteDebeRestarUnPunto
    title alResponderIncorrectamenteDebeRestarUnPunto
    hide footbox

    '"opcion:Opcion" as opcion

    actor "test:Junit" as test
     ' le asigno el alias para que sea mas sencillo de hacer referencia


    test -> PreguntaCreador: crearPregunta(pregunta: VFconPenalidad, opciones: Opcion)
    
    create "preguntaVFconPenalidad: Preguntable" as preguntaVFconPenalidad
    PreguntaCreador -> preguntaVFconPenalidad: <<create>>
    
    PreguntaCreador --> test: preguntaVFconPenalidad

    test -> "opcionIncorrecta:Opcion" as opcionIncorrecta : generarOpcion(contenido:str, valor:Bool)
    opcionIncorrecta --> test: opcionIncorrecta

    
    test -> preguntaVFconPenalidad: establecerPuntuacion(opcionIncorrecta: Opcion)
    preguntaVFconPenalidad -> opcionIncorrecta: esCorrecta()
    opcionIncorrecta --> preguntaVFconPenalidad: false

    preguntaVFconPenalidad --> test: -1


@enduml