@startuml

title Aplicar Multiplicador a Pregunta sin Penalidad

Kahoot -> Ronda: responder(jugador, opciones, multiplicador)
Ronda -> Preguntable: establecerPuntuacion(opciones, multiplicador)
Preguntable -> Ronda: puntos
Ronda -> Jugador: sumarPuntos(puntos)

@enduml