@startuml

title Aplicar Multiplicador a Pregunta Con Penalidad

Kahoot -> Ronda: responder(jugador, opciones, multiplicador)
Ronda -> Preguntable: establecerPuntuacion(opciones)
Preguntable -> Ronda: puntos
Ronda -> Preguntable: aplicarMultiplicador(puntos, multiplicador)
Preguntable -> Ronda: puntos
Ronda -> Jugador: sumarPuntos(puntos)

@enduml