@startuml
!include vista.iuml
title Modelo de CargadorPreguntas
class Kahoot {
    - controladorPanel: ControladorPanel
    + iniciar()
    - cargarPantallaPrincipal()
}

class CargadorPreguntas <<Singleton>> {
    - instancia: CargadorPreguntas
    - preguntas: List<Preguntable>
    + {static} obtenerInstancia(): CargadorPreguntas
    + {static} obtenerInstancia(rutaArchivo: String)
    - CargadorPreguntas(rutaArchivo: String)
    + obtenerPreguntas(): List<Preguntable>
}

class Pregunta {
    - tipoPregunta: TipoPregunta
    - datoPregunta: DatoPregunta
    + parsearPregunta(): Preguntable
    + getTipoPregunta(): TipoPregunta
    + setTipoPregunta(tipoPregunta: TipoPregunta)
    + getDatoPregunta(): DatoPregunta
    + setDatoPregunta(datoPregunta: DatoPregunta)
}

class CreadorPregunta{
    + {static} crearPregunta(tipoPregunta: TipoPregunta, pregunta: Str, opciones:List<Opcion>): Preguntable
}

interface Preguntable{
    + obtenerOpciones():List
    + obtenerPregunta():str
    + obtenerTipoPregunta():TipoPregunta
    + establecerPuntuacion(opciones: T, multiplicador: MultiplicableStrategy, exclusividad: Exclusividad): int
}

enum TipoPregunta{
    VerdaderoFalsoClasico
    VerdaderoFalsoPenalidad
    MultipleChoiceClasico
    MultipleChoiceParcial
    MultipleChoiceConPenalidad
    OrderedChoice
    GroupChoice
}

Kahoot -down-> CargadorPreguntas
CargadorPreguntas -> Pregunta
Pregunta -> CreadorPregunta
Pregunta o-right-> TipoPregunta
CreadorPregunta -up->TipoPregunta
CreadorPregunta -down-> Preguntable

@enduml