@startuml
!include vista.iuml
title Un jugador responde con exclusividad BackEnd
hide footbox

    ControladorPanel -> Partida: responder(opcionesSeleccionadas, multiplicador, exclusividadSeleccionada)

    Partida -> Ronda: responder(opcionesSeleccionadas, multiplicador, exclusividadSeleccionada)

    Ronda -> Preguntable: establecerPuntuacion(opcionesSeleccionadas, multiplicador, exclusividad)

    Preguntable -> Exclusividad: activarExclusividad()

    Preguntable --> Ronda: puntos

    activate Ronda

    Ronda -> Ronda: cambiarJugadorTurno()

    Ronda -> Ronda: actualizarEstadoRonda()

    Partida -> Partida: actualizarTurno()

    deactivate Ronda

@enduml