@startuml
title Creación Verdadero Falso Con Penalidad Con Opciones Validas

Kahoot -> CreadorPregunta: CreadorPregunta.crearPregunta(TipoPregunta.VerdaderoFalsoPenalidad, pregunta, opciones)
CreadorPregunta -> VerdaderoFalsoPenalidad: new VerdaderoFalsoPenalidad(pregunta, opciones)

activate VerdaderoFalsoPenalidad
VerdaderoFalsoPenalidad -> VerdaderoFalsoPenalidad: validarOpciones(opciones)
VerdaderoFalsoPenalidad -> CreadorPregunta: new VerdaderoFalsoPenalidad(pregunta, opciones)
deactivate VerdaderoFalsoPenalidad

CreadorPregunta --> Kahoot: new VerdaderoFalsoPenalidad(pregunta, opciones)
@enduml