@startuml
title Modelo Inicial del Juego
skinparam classAttributeIconSize 0

class Partida{
}


class Jugador{
    - puntos: int
    - nombre: string

    + obtenerNombre():string
    + obtenerPuntaje():int
    + sumarPuntos():void
}

interface Preguntable{
    + {abstract}obtenerOpciones(): List<Opcion>
    + {abstract}establecerPuntuacion(List<Opcion>): int
    + {abstract}obtenerPregunta(): str

}

class Ronda{
    ' - jugadores: List<Jugador>
    ' - pregunta: Preguntable

    + obtenerJugadores(): List<Jugador>
    + obtenerPregunta():Preguntable
    + responder():void
}

interface Modificable{
    + aplicarModificador(jugadorConModificador: Jugador, otroJugador: Jugador): int
}



Partida "1"-left->"*" Jugador

Partida "1"->"*" Preguntable

Partida "1" -down->"*" Ronda
Ronda "1  "-down..>"*" Modificable
Ronda "1" o-up->"*" Preguntable
Ronda "1" o-left->"*"Jugador


@enduml